### ISSUE TITLE
Add missing License

### ISSUE THREAD

**Issue by nicolasStevenin** [bmizerany/pat#50]
Hello,

Could you add the License file please ?

Thank you

**Comment by mark-rushakoff** [comment]
The README indicates an MIT license, but the github UI isn't picking it up. ping @bmizerany.

**Comment by asmaloney** [comment]
(probably related)

Without the license, the [docs the README point at](http://godoc.org/github.com/bmizerany/pat) say:

> Documentation not displayed due to license restrictions.

**Comment by j0holo** [comment]
You need to add a dedicated LICENSE file otherwise it is not explicit enough. PR #43 is already doing that.

**Comment by bmizerany** [comment]
Done.
